### ISSUE TITLE
Duda sobre como empezar

### ISSUE THREAD

**Issue by iromanm** [scm-spain/karyon-rest-router#1]
Hola Víctor,

Estoy intentando ejecutar tu proyecto, pero estoy teniendo algún problema. Hasta ahora he estado trabajando con el proyecto "scm-spain/Microservice-Template" donde  hay una clase "AppRouter" donde van los endPoints. Esta clase es la que se define en una tarea "runApp"  como clase principal.

Tu proyecto tiene una estructura algo diferente. ¿Donde deberían ir los endpoints? ¿Cual sería la clase principal?

Gracias

**Comment by victuxbb** [comment]
Hola Ignasi, pues mira, ahora mismo, estoy acabando de "deployar" el módulo a maven central.
Con esto, mi intención es que para usar el módulo, simplemente lo añadas como dependencia en gradle, por ejemplo:

```groovy
dependencies {
       compile 'com.scmspain.karyon:karyon-rest-router:1.0.0'   
}
```
Y a partir de aquí, simplemente con unas configuraciones que detallaré en github estará listo y funcionando.
Entre hoy y mañana lo tendré listo :)

Puedes esperar?

Gracias!

**Comment by iromanm** [comment]
Ok Perfecto.
Espero un poco pues.

**Comment by victuxbb** [comment]
Hola ignasi, aunque todavía no aparece en maven central, ya se puede usar desde el repositorio de releases de oss.sonatype.org 
Te paso un ejemplo de como he configurado gradle y ya puedes usarlo:

```groovy
repositories {
    mavenCentral()
    maven(){
        url "https://oss.sonatype.org/content/repositories/releases/"
    }
}

dependencies {
    compile 'com.scmspain.karyon:karyon-rest-router:1.0'
    ...
    ...
    ...
}

```
También he actualizado la doc, si algo no te queda claro, si quieres lo hablamos en persona :)

Gracias!

**Comment by victuxbb** [comment]
Hola de nuevo, bueno finalmente ya la han publicado en maven central :)
Ya no hace falta que añadas un repositorio nuevo, simplemente añade la dependencia como lo harías con cualquier otra librería. Aquí puedes ver la librería:

http://search.maven.org/#artifactdetails%7Ccom.scmspain.karyon%7Ckaryon-rest-router%7C1.0%7Cjar

Y la linea de gradle:

```groovy
compile 'com.scmspain.karyon:karyon-rest-router:1.0'
```

**Comment by iromanm** [comment]
Gracias Víctor.
Me lo miro
