### ISSUE TITLE
Optional QueryParams 

### ISSUE THREAD

**Issue by padilo** [scm-spain/karyon-rest-router#10]
We have a path endpoint that has an optional Boolean as a parameter, if we send it to true or false it works as expected, but if the parameter is not send the value is false and we expect a null value.

I think it should work putting this value to null, as a feature it would be very nice if the QueryParam annotation has a defaultValue attribute if it's not set imho it should set null if parameters aren't send.

Support of Optional it would be very appreciated too :)

**Comment by victuxbb** [comment]
Hi, QueryParam has a defaultValue attribute already

```java

@Path(value = "/example_query_param_default/{id}", method = HttpMethod.GET)
    public Observable<Void> getEndpointResource(... @QueryParam(value = "filter",defaultValue = "forlayo", required=true) String filter) {

               return response.writeStringAndFlush(jsonResponse);

  }

```

**Comment by victuxbb** [comment]
@padilo the last release is v1.2.1 don't forget to be updated, in previous versions it was some error with boolean types I think...

**Comment by padilo** [comment]
Sorry, you are right about the default-value, but I think it should return a null by default instead, imo.

We can't set null as default value due (it's not possible). Maybe a good idea to remove the default value to attribute 'default-value' and if it's not set call the method path annotated with a null if the query param is not set in the request, or Optional.empty() if the parameter is Optional.
