### ISSUE TITLE
Getting pathParams also brings the querystring append

### ISSUE THREAD

**Issue by raulhm** [scm-spain/karyon-rest-router#2]
I'm starting using this module, and I find out an issue for use it when there's a querystring. In my case I want to search for the car models depending on a car brand 

i.e. http://myapi.com/fieldrules/model?brand=opel

This is the code I use:
``` java
    @Path(value = "/fieldrules/{fieldId}", method = HttpMethod.GET)
    public Observable<Void> getRulesByFieldId(HttpServerRequest<ByteBuf> request, HttpServerResponse<ByteBuf> response, Map<String,String> pathParams) {

        String formId = pathParams.getOrDefault("fieldId", "");
        formId = formId.substring(0, formId.indexOf("?"));
``` 

When I got the formId I got "model?brand=opel", so I was forced to get the part I needed.

**Comment by victuxbb** [comment]
Hi @raulhm ! It's a normal behavior because there isn't support for QueryParams still.

I will try to add this functionality in the next couple of days, maybe I will create a new annotation like...

```java
@Path( value = "/fieldrules/model", method = HttpMethod.GET)
@QueryParam("brand")
public Observable<Void> getRulesByFieldId(HttpServerRequest<ByteBuf> request, HttpServerResponse<ByteBuf> response, Map<String,String> pathParams, Map<String,String> queryParams) {

String brand = queryParams.getOrDefault("brand", "forlayoBrand");
```

**Comment by raulhm** [comment]
great!

**Comment by victuxbb** [comment]
Hi @raulhm, I realeased a new version with support to path params and query params :)

Check the documentation on [examples](https://github.com/scm-spain/karyon-rest-router/wiki/Routing-1.0-Examples) for more info :)

**Comment by raulhm** [comment]
:+1:
